### ISSUE TITLE
A feature cycle was found

### ISSUE THREAD

**Issue by ChromaPIE** [GregTechCEu/GregTechCEu-1.19#430] opened 2023-09-29 09:27 UTC
### GregTech CEu Version

1.0.12.f build 211

### Recipe Viewer Installed

REI

### Environment

SP

### Cross-Mod Interaction

Unsure

### Expected Behavior

No crash

### Actual Behavior

Crash.

Related part in log: https://hastebin.com/share/unekecogip.ruby

### Steps to Reproduce

creative fly around, boom.

**Comment by rinOfTheStars** [comment] 2023-09-30 00:04
Duplicate of #409 and #355

**Comment by ChromaPIE** [comment] 2023-10-01 19:55
This and #301 might have been fixed by the latest massive update on Terralith's side. I'll let yall know if the issue persists.

**Closed as completed** 2023-10-21 10:07 UTC
Labels: type: bug
