### ISSUE TITLE
Steam Oven doesn't smelt if items are less than 8

### ISSUE THREAD

**Issue by DoneTCT** [GregTechCEu/GregTechCEu-1.19#1243] opened 2024-05-12 21:16 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.2.2

### Recipe Viewer Installed

None

### Environment

MultiPlayer

### Cross-Mod Interaction

No

### Other Installed Mods

Playing GT Community Pack 1.8.0

### Expected Behavior

Before the update the furnace smelted all items regardless of the number.

### Actual Behavior

Now if they are less than 8 they don't get smelted.

### Steps to Reproduce

put less than 8 pieces of smeltable items in the furnace and it stays idle.
when the number reaches 8 it smelts.

### Additional Information

i've not tested in singleplayer.
furnace had steam.
rebuilt every block just in case something bugged out since the update, result is the same.
![2024-05-12_23 15 19](https://github.com/GregTechCEu/GregTech-Modern/assets/48444041/ead99564-e633-4c07-aa56-bc113a198dd2)

![2024-05-12_23 18 44](https://github.com/GregTechCEu/GregTech-Modern/assets/48444041/d916f73d-eb10-4cd1-9c94-b9fbf438c234)

**Comment by DoneTCT** [comment] 2024-05-12 21:20
idk if this happens with the multyblock macerator as well...

**Comment by Wyrmlet** [comment] 2024-05-13 07:32
Same thing is happening to me with a multismelter after the recent update. With nichrome coils, those only accept 64 of the same item at a time, without that it does not work.

**Comment by screret** [comment] 2024-05-13 07:34
duplicate of #1223 .

**Closed as not planned by screret** 2024-05-13 07:34 UTC
Labels: type: bug
