### ISSUE TITLE
[Bug] - Checking the recipe on an empty slot any GT block causes the game to crash

### ISSUE THREAD

**Issue by StellaBiscuit** [GregTechCEu/GregTechCEu-1.19#742] opened 2024-01-12 16:16 UTC
### GregTech CEu Version

1.20.1-1.0.20.b

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

To do nothing, like any other slots

### Actual Behavior

JEI tries to read the recipe of the item "minecraft:air" prompting a crash as it isn't an actual item that can be viewed

### Steps to Reproduce

1 - Place a GT block that has slots (like a crate)
2 - Press U/R (whatever button to check uses/recipes) on an empty slot
3 - Crash!

### Additional Information

 As explained above, JEI tries to get the recipes/uses of an air item, which is not possible and unintended, causing the game to crash

I was playing with other mods, but due to the nature of the crash, there is no reason for them to cause issue reproducing the bug
Crash Report :
[crash-2024-01-12_11.11.29-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/13921443/crash-2024-01-12_11.11.29-client.txt)

**Comment by StellaBiscuit** [comment] 2024-01-13 03:29
Updated, the crash happens on any machine/block from GT

**Comment by screret** [comment] 2024-01-16 12:24
duplicate of #733.

**Closed as not planned by screret** 2024-01-16 12:24 UTC
Labels: type: bug
