### ISSUE TITLE
Crash on Fabric 1.20.1 - World Gen

### ISSUE THREAD

**Issue by Martmists-GH** [GregTechCEu/GregTechCEu-1.19#409] opened 2023-09-23 15:09 UTC
### GregTech CEu Version

1.20.1-1.0.12.e

### Recipe Viewer Installed

REI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

The world generates properly.

### Actual Behavior

The game crashes with the following message, disappearing once GTCEu is removed: 

java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:birch_forest]=net.minecraft.class_1959@4bc654a3}]

Full logs: https://mclo.gs/xD0Lck7

### Steps to Reproduce

1. Launch the game
2. Create a world
3. The game crashes

**Comment by rinOfTheStars** [comment] 2023-09-29 23:54
That's concerning. Might be a duplicate of #355? The bug looks nearly identical...

**Comment by Martmists-GH** [comment] 2023-10-03 16:34
Seems to be fixed as of Terralith 2.4.7

**Comment by Martmists-GH** [comment] 2023-10-03 16:48
Actually nope, one world I created was fine but the other crashed.

**Comment by rinOfTheStars** [comment] 2023-10-03 17:07
I wouldn't close it anyways even if Terralith changes things to not conflict—this bug isn't caused by Terralith, but something on GTCE-Modern's side, if #335 and #430 are any indication (they're the exact same crash caused by different biome feature conflicts)

**Comment by mikerooni** [comment] 2023-10-03 17:20
Yeah, please don't close it just yet.

Can you consistently reproduce this issue with a specific seed (and possibly specific coordinates), or does it happen completely at random?

Also, which modloader and Minecraft version are you using?

**Comment by rinOfTheStars** [comment] 2023-10-03 17:45
I know that it seems to be entirely biome-specific and based off what biomes the game is trying to load for worldgen, considering the version of this bug that occurs on QFAPI happens when the Bamboo Forest biome is present—generating and loading into a superflat world works fine. 

Seems to be only present on FAPI with biome mods and QFAPI with that biome specifically as well; haven't seen any reports of this on (Neo)Forge. Guessing there's an implementation issue in the FabriQuilt-specific code when it comes to worldgen, and for whatever reason QSL or QFAPI's mixins cause it to happen more frequently than with just FAPI.

**Closed as completed** 2023-10-22 07:18 UTC
Labels: type: bug
