### ISSUE TITLE
Tools not set as crafting remainders in EMI

### ISSUE THREAD

**Issue by KP2048** [GregTechCEu/GregTechCEu-1.19#1423] opened 2024-06-15 23:07 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.2.3.a

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

- AE Additions
- AE2WTLib
- AEInfinityBooster
- AI\-Improvements
- Absolutely Unbreakable
- Ad Astra
- Additional Structures
- Advanced Generators
- Advanced Peripherals
- Advancement Plaques
- Alex's Mobs
- AlmostUnified
- Alternate Current
- Ambient Environment
- AmbientSounds
- Amendments
- Angel Ring 2
- Animated Doors
- Apotheosis
- Apotheotic Additions
- Apothic Attributes
- Apothic Curios
- AppleSkin
- Applied Botanics
- Applied Cooking
- Applied Energistics 2
- Applied Mekanistics
- Aquaculture 2
- Architectury
- Areas
- Ars Creo
- Ars Nouveau
- Ars Ocultas
- Ars Énergistique
- Artifacts
- Ascension Megamons
- Athena
- AttributeFix
- Auto Third Person
- Axes Are Weapons
- BOZOID
- Bad Packets
- Balm
- Baubley Heart Canisters
- BdLib
- Better Advancements
- Better Animations Collection
- Better Combat
- Better Mods Button
- Better Third Person
- Better Title Screen
- Better village
- BetterF3
- Bettercrafting
- Biome Makeover
- Biomes O' Plenty
- Blood Magic
- Blue Flame Burning
- Blueprint
- Boat Break Fix
- Boat Item View
- Bookshelf
- Botania
- Botarium
- Bounced
- Bountiful
- Building Gadgets 2
- Bygone Nether
- CBMultipart
- CC: Tweaked
- Caelus API
- Canary
- Carpeted
- Carry On
- CatJammies
- Catalogue
- Cerbons API
- Charging Gadgets
- Chipped
- ChoiceTheorem's Overhauled Village
- Chunky
- Citadel
- Clean Swing Through Grass
- ClearDespawn
- Cloth Config v10 API
- Clumps
- CoFH Core
- Cobbled Mod
- Cobblemon
- Cobblemon Capture XP
- Cobblemon Challenge
- Cobblemon Integrations
- Cobblemon O' Plenty
- Cobblemon Spawn Notification
- Cobblemon: Simple TM's
- CobblemonTrainers
- Cobblepedia
- CodeChicken Lib
- Collective
- Comforts
- CommonCapabilities
- Configured
- Connected Glass
- Connectivity Mod
- Connector\-1\.0\.0\-beta\.28\+1\.20\.1
- Continents
- Controlling
- CookingForBlockheads
- Corail Tombstone
- Corail Woodcutter
- CorgiLib
- CosmeticArmorReworked
- CraftPresence
- CraftedCore
- CraftingTweaks
- Create
- Create Applied Kinetics
- Create Big Cannons
- Create Crafts & Additions
- Create Deco
- Create Enchantment Industry
- Create Ender Transmission
- Create Jetpack
- Create Railways Navigator
- Create Slice & Dice
- Create Stuff & Additions
- Create: Bells & Whistles
- Create: Central Kitchen
- Create: Cobblemon Factory
- Create: Copycats\+
- Create: Interactive
- Create: New Age
- Create: Station Decor
- Create: Train Perspective
- CreativeCore
- Cristel Lib
- Croptopia
- Cucumber Library
- Cupboard utilities
- Curios API
- Current Game Music Track
- Cyclops Core
- Dank Storage
- DarkUtilities
- Dashboard
- Deeper and Darker
- Delightful
- Diagonal Fences
- Ding
- Dismount Entity
- Distant Horizons
- DistractingTrims
- Do a Barrel Roll
- Domum Ornamentum
- Double Doors
- Drippy Loading Screen
- Dungeon Crawl
- Dungeons Enhanced
- Dungeons and Taverns
- Durability Tooltip
- Dynamic Crosshair
- Dynamic Electricity
- Dynamic FPS
- DynamicTrim
- EMI
- EMI Loot
- EMI Trades
- Easy Anvils
- Easy Elytra Takeoff
- Easy Magic
- Easy Villagers
- Eccentric Tome
- EdivadLib
- Effortless Building
- Electrodynamics
- Elenai Dodge
- Elevator Mod
- Elytra Slot
- Embeddium
- Embeddium Extra
- Emotecraft
- Enchanting Infuser
- Enchantment Transfer
- EnchantmentDescriptions
- End Remastered
- End's Delight
- Ender IO
- Ender's Delight
- EnderStorage
- EndlessBiomes
- Enhanced Celestials
- Ensorcellation
- Entangled
- Entity Model Features
- Entity Texture Features
- EntityCulling
- Equipment Compare
- Euphoria Patcher
- Explorer's Compass
- Explorify
- Extra Disks
- Extra Enchantments and Curses
- ExtraStorage
- Extreme Reactors
- Extreme Sound Muffler
- FTB Chunks
- FTB Library
- FTB Teams
- FTB Ultimine
- FallingTree
- FancyMenu
- Farmer's Delight
- Farming for Blockheads
- Fast Suite
- Fast Workbench
- FastFurnace
- Fastload\-Reforged
- Feathers
- Ferrite Core
- Flux Networks
- Forbidden & Arcanus
- ForgeEndertech
- Forgified Fabric API
- Forgiving world mod
- Framework
- From The Fog
- Fuel Goes Here
- Functional Storage
- Fusion
- Galosphere
- GeckoLib 4
- GeckoLibIrisCompat
- Geophilic
- Get It Together, Drops\!
- Global Packs
- Goblin Traders
- Gpu memory leak fix
- Greate
- GregTech
- Gregic Energistics
- Guard Villagers
- Hang Glider
- Healing Campfire
- Highlight
- Highlighter
- Iceberg
- ImmediatelyFast
- Immersive Structures
- In\-game NBTEdit Reborn
- Incendium
- Industrial Foregoing
- Infinity with Mending
- IntegratedCrafting
- IntegratedDynamics
- IntegratedTunnels
- Inventory Essentials
- Inventory Tabs
- Iron Chests: Restocked
- Iron's Spells 'n Spellbooks
- ItemPhysic
- JAOPCA
- JAOPCA Extras
- Jade
- Jade Addons
- JamLib
- JourneyMap Integration
- JourneyMap\-Teams
- Journeymap
- Jumpy Boats
- Just Enough Advancements
- Just Enough Beacons
- Just Enough Breeding
- Just Enough Effects Descriptions
- Just Enough Items
- Just Enough Mekanism Multiblocks
- Just Enough Professions \(JEP\)
- Just Enough Resources
- Just Zoom
- Kambrik
- Kiwi Library
- KleeSlabs
- Konkrete
- Kontraption
- Kotlin for Forge
- Krypton Reforged
- KubeJS
- KubeJS Create
- L2 Library
- LAN World Plug\-n\-Play
- Large Ore Deposits
- LaserIO
- Leaves Be Gone
- Legendary Tooltips
- LibX
- Library ferret
- Light Overlay
- Load My F\*\*\*ing Tags
- Log Begone
- Logprot
- Lootintegrations mod
- Lootr
- ME Requester
- Macaw's Bridges
- Macaw's Doors
- Macaw's Fences and Walls
- Macaw's Furniture
- Macaw's Lights and Lamps
- Macaw's Paths and Pavings
- Macaw's Roofs
- Macaw's Trapdoors
- Macaw's Windows
- Magic Mirror Mod
- Mahou Tsukai
- McJtyLib
- Measurements
- Mekanism
- Mekanism: Additions
- Mekanism: Generators
- Mekanism: Tools
- Melody
- Memory Leak Fix
- Memory Usage Screen
- MidnightLib
- Mindful Darkness
- MineColonies
- Minecraft Transit Railway
- Mining Gadgets
- MixinInHeaven
- MmmMmmMmmmmm
- Mob Grinding Utils
- Mod Name Tooltip
- Modern Startup QOL
- ModernFix
- Modonomicon
- Modular Forcefields
- Modular Golems
- Monomorphism
- Moonlight Library
- More Crafting Tables Mod
- More Geodes Reforged
- More Mob Variants
- More Red
- More Villagers
- MoreBookshelves
- Mouse Tweaks
- Multi\-Piston
- Mystical Agriculture
- MythicBotany
- Naturalist
- Nature's Compass
- Neat
- Necronomicon
- Neko's Enchanted Books
- Neruina
- Nether's Delight
- Netherite Old Craft
- No Chat Reports
- No LAN Cheating
- No Telemetry
- Not Enough Crashes
- Not Enough Recipe Book
- NotEnoughAnimations
- Nullscape
- ObsidianUI
- Occultism
- Ocean's Delight
- OctoLib
- Oculus
- Oculus Flywheel Compat
- Old Potions
- Overflowing Bars
- OverpoweredMending
- PKGBadges
- Panorama Screens
- Panoramica
- Patchouli
- Pehkui
- Personality
- Pet Your Cobblemon
- Philips Ruins
- Pick Up Notifier
- Placebo
- Player Animator
- PneumaticCraft: Repressurized
- Polymorph
- Polymorphic Energistics
- Prism
- Productive Bees
- Puzzles Lib
- Quark
- RFToolsBase
- RFToolsBuilder
- RFToolsControl
- RFToolsStorage
- RSInfinityBooster
- RSRequestify
- Railcraft Reborn
- Random Village Names
- ReMorphed
- Realm RPG: Fallen Adventurers
- Rebind Narrator
- RebornStorage
- Rechiseled
- Rechiseled: Create
- RecipeDumper
- Refined Cooking
- Refined Polymorphism
- Refined Storage
- Refined Storage Addons
- Regions Unexplored
- Relics
- Repurposed Structures
- Reroll Enchants
- Resourceful Lib
- Resourcefulconfig
- Rhino
- Right Click Harvest
- RotomPhoneCobblemon
- Roughly Enough Config Screens
- Rubidium Dynamic Lights
- Runelic
- Saturn
- Scalable Cat's Force
- Screenshot to Clipboard
- Seamless
- Searchables
- Sebastrn Lib
- Serene Seasons
- Shield Expansion
- Shoulder Surfing Reloaded
- Shrink
- ShulkerBoxTooltip
- Sidekick
- Silent Gear
- Silent Lib
- Simple Backups
- Simple Inventory Sorter
- Simple Magnets
- Simple Storage Network
- Simple Voice Chat
- Simply Swords
- Sinytra Connector
- Sit
- Sky Villages
- SmartBrainLib
- Smarter Farmers
- Smooth Boot \(Reloaded\)
- Smoothchunk mod
- Snow Under Trees
- Snow\! Real Magic\!
- Sophisticated Backpacks
- Sophisticated Core
- Sophisticated Storage
- Sound Physics Remastered
- Spawn Animations
- Starter Kit
- Stellar View
- Stoneworks
- Storage Drawers
- Structure Gel API
- Structurize
- Subterrestrial
- SuperMartijn642's Config Library
- SuperMartijn642's Core Lib
- Supplementaries
- Tax Free Levels
- Tectonic
- Tempad
- TerraBlender
- Terralith
- Tetranomicon
- The Aether
- The Twilight Forest
- Thermal Cultivation
- Thermal Dynamics
- Thermal Expansion
- Thermal Foundation
- Thermal Innovation
- Thermal Integration
- Thermal Locomotion
- Time In A Bottle
- Time in a bottle Curio Support
- Timeless & Classics Guns: Zero
- Tiny Coal
- Tips
- Titanium
- Toggle Enchantments
- Tom's Simple Storage Mod
- Tome of Blood: Rebirth
- Tomtaru's Cobblemon & Farmer's Delight Tweaks
- ToolStats
- Torchmaster
- TownTalk
- Towns and Towers
- Trading Post
- Translocators
- Trash Cans
- TrashSlot
- Traveler's Titles
- Twilight's Flavor & Delight
- UI Library Mod
- Underground Villages Mod
- Unimplemented Items
- Universal Grid
- VS Eureka Mod
- Valhelsia Core
- Valkyrien Skies 2
- Vanilla Refresh
- Vertical Slabs Compat
- Village Spawn Point
- Villager Names
- Visual Workbench
- WI Zoom
- Walkers
- WaveyCapes Mod
- Waystones
- What's That Slot
- When Dungeons Arise
- Why stacks of 16?
- World Host
- World Preview
- XNet
- XNet Gases
- YDM's Weapon Master
- YUNG's API
- YUNG's Better Desert Temples
- YUNG's Better Dungeons
- YUNG's Better End Island
- YUNG's Better Jungle Temples
- YUNG's Better Nether Fortresses
- YUNG's Better Ocean Monuments
- YUNG's Better Strongholds
- YUNG's Better Witch Huts
- YUNG's Bridges
- YUNG's Extras
- YUNG's Menu Tweaks
- Yeetus Experimentus
- YetAnotherConfigLib
- Zero CORE 2
- Zeta
- betterchunkloading mod
- biomemusic mod
- chisels\-and\-bits
- chunksending mod
- clickadv mod
- clientcrafting mod
- cobblemonrider
- fastasyncworldsave mod
- flib
- mutil
- recipeessentials mod
- spark
- stylecolonies mod
- tetra

### Expected Behavior

Tools should not be counted multiple times in the cost and should end up in the remainders in the crafting tree

### Actual Behavior

y'all's custom hook thing that sets the durability causes emi to not be able to autodetect it

### Steps to Reproduce

use the recipe tree on any recipe that uses gt tools

**Comment by screret** [comment] 2024-06-16 17:03
> y'all's custom hook thing that sets the durability causes emi to not be able to autodetect it
IDK about that, we do it exactly the same as most of everyone else.

**Comment by screret** [comment] 2024-06-16 17:04
also duplicate of #994

**Closed as not planned by screret** 2024-06-16 17:04 UTC
Labels: type: bug
