### ISSUE TITLE
When the input quantity is less than the maximum parallel number, the machine does not work.

### ISSUE THREAD

**Issue by nutant233** [GregTechCEu/GregTechCEu-1.19#1223] opened 2024-05-09 11:59 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1-1.2.1-build_642

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

o

### Other Installed Mods

None

### Expected Behavior

After placing the item, the machine will operate.

### Actual Behavior

The machine is not running.

### Steps to Reproduce

Place a single iron ingot into the steam macerator.

**Comment by YiRanMushroom** [comment] 2024-05-16 10:44
This does not seemed to be fixed yet, the parallel logic is still not correct, like the multismelter cannot smelt item with amount less than the corresponding parallel amount.

**Comment by screret** [comment] 2024-05-16 10:54
The fix isn't merged, and the issue is open.
What'd you expect?

**Comment by YiRanMushroom** [comment] 2024-05-16 11:10
I thought that was merged, bc I saw the 2 tasks done. Sorry.

**Closed as completed** 2024-05-16 19:37 UTC
Labels: type: bug
