### ISSUE TITLE
Upgrade kit (LV>MV, MV>HV, etc...)

### ISSUE THREAD

**Issue by Uchiwars** [GregTechCEu/GregTechCEu-1.19#1809] opened 2024-08-23 14:09 UTC
### Feature Description

Hello,

Can you add a "upgrade kit"? to upgrade a LV machine to his MV version for example? Because we have to craft a lot of machine per tier to get to the next, and i feel that it's a waste everytime... (arc furnace doesn't give enough of the materials back)

Thanks and have a great day

**Comment by JuiceyBeans** [comment] 2024-08-23 14:16
Works as intended, will probably never get implemented in base GT

**Comment by Uchiwars** [comment] 2024-08-23 14:51
Ok i understand, then is it possible to add the disassembler? it was in [Gregtech 5](https://ftb.fandom.com/wiki/Disassembler_(GregTech_5))

**Comment by Ghostipedia** [comment] 2024-08-23 15:02
The disassembler was removed in favor of Arc Recycling/Maceration Recycling as 100% reclamation of older hardware is way too strong. Arc/Maceration recycling at least gives you the raw materials back, excluding the circuits. Which is a fair trade as raw materials are always useful.

Going to close this issue as "Not Planned"

**Closed as not planned by Ghostipedia** 2024-08-23 15:02 UTC
Labels: type: feature, Wontfix
