### ISSUE TITLE
Acidic fluids don't function

### ISSUE THREAD

**Issue by Kasyu** [GregTechCEu/GregTechCEu-1.19#2524] opened 2024-12-10 02:34 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.5.3

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Pack is gregtech community pack modern

### Expected Behavior

The questbook lists hydrochloric acid and sulfuric acid as having an acidic hazard, and should function as stated there, with a marker indicating being acidic, and pipes not listed as carrying acids burning and voiding fluid

### Actual Behavior

no fluids use the acidic tag, including sulfuric and hydrochloric acid, and can be transported by regular pipes just fine

### Steps to Reproduce

open gregtech community pack modern
place drum of sulfuric acid on pipe not listed as handling acids
allow draining from drum
nothing ends up happening with acidity

**Comment by Wyrmlet** [comment] 2024-12-14 23:43
Bump. This has been a thing for a while now, too! Pipe overheating does seem to work (wooden pipes can't hold steam), so this is definitely specific for acids.

**Comment by jtuc** [comment] 2024-12-16 18:07
I can confirm this is still an issue in 1.5.5 as of 46e27f698f8c004fab9d976f87cc86f26a1e3863.

It looks like the issue is down to how fluid properties are handled - fluids have a collection of `FluidAttributes`, and acids should have the `FluidAttributes.ACID` attribute. However, it seems like when fluids are registered, only the "flowing" variant of the fluid gets the attributes, and the `FluidPipeBlockEntity` checks if the "source" fluid has the attribute (which it does not.)

![image](https://github.com/user-attachments/assets/5a87a538-b222-4071-abd8-3d31042493f0)

I spent a while trying to dig through the registry callback logic to see if I could fix this, but got a bit lost. Manually adding the `ACID` attribute to the source fluid did dissolve my pipes though.

**Comment by krossgg** [comment] 2024-12-16 18:52
Known issue. Solution unknown. Not a priority at the moment, but will be fixed eventually.

**Comment by YoungOnionMC** [comment] 2024-12-17 00:12
Fixed in #2560

**Closed as completed by YoungOnionMC** 2024-12-17 00:12 UTC
Labels: type: bug
