### ISSUE TITLE
Balm and GTCEu:M Crash

### ISSUE THREAD

**Issue by desagas** [GregTechCEu/GregTechCEu-1.19#1740] opened 2024-08-16 15:07 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.21-1.3.1

### Minecraft Version

1.21

### Recipe Viewer Installed

No Recipe Viewer

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

LDLib 1.21-1.0.26.b

and

Balm 1.21.1-21.0.15

### Expected Behavior

Minecraft loads past mixins.

### Actual Behavior

Minecraft does not load past mixins.

[crash-2024-08-16_08.50.48-client.txt](https://github.com/user-attachments/files/16638542/crash-2024-08-16_08.50.48-client.txt)

### Steps to Reproduce

Install all mods listed above. GTCEu works by itself with LDLib; Balm works by itself.

Add the two together, and it will no longer load.

### Additional Information

Other issues are similar, and I assume related, however, not a single one I looked at represented exactly what happened to my in SP. If it is identical, I apologize, as the Balm mod shows up in almost every occurrence of GTCEu crashes.

**Comment by screret** [comment] 2024-08-16 15:08
latest.log please

**Comment by desagas** [comment] 2024-08-16 15:23
https://pastebin.com/PYrMvMSG

**Comment by desagas** [comment] 2024-08-16 15:23
[debug.log](https://github.com/user-attachments/files/16638686/debug.log)

**Comment by screret** [comment] 2024-08-16 15:25
not related to balm. GT's JEI integration is still out of date on 1.21. downgrade JEI.

**Comment by screret** [comment] 2024-08-16 15:26
duplicate of #1663 .

**Closed as not planned by screret** 2024-08-16 15:26 UTC

**Comment by desagas** [comment] 2024-08-16 15:39
Oh, I updated the wrong logs, sorry. But now, I can not find the right ones, nor can I reproduce the crash. Strange. Sorry about that. Its like the twilight zone.!
