### ISSUE TITLE
Custom recipe using CWU output doesn't work

### ISSUE THREAD

**Issue by MrLaCar** [GregTechCEu/GregTechCEu-1.19#1473] opened 2024-06-22 18:25 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.0.a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Not the cross-mod interaction

### Expected Behavior

can generate computation

### Actual Behavior

I create a recipe use to generate computation but when i enter the game the recipe doesn't work even though i put right item
My codes for generate computation is CWUt(-512) in kjs file

### Steps to Reproduce

I didn't do any other changes

### Additional Information

Is there anyway that allows me to generate computation by using custom recipes in kjs file or build a special machine with specific logic?

**Comment by screret** [comment] 2024-06-25 08:22
duplicate of #1139

**Closed as not planned by screret** 2024-06-25 08:22 UTC
Labels: type: bug

**Comment by MrLaCar** [comment] 2024-06-25 08:41
So it means It have to waiting for a new addon or something else to achieve this function (output cwu) in kjs?
