### ISSUE TITLE
The dynamic mapping of multi-block bronze oven is abnormal.

### ISSUE THREAD

**Issue by TheDreamsCreator** [GregTechCEu/GregTechCEu-1.19#1754] opened 2024-08-17 20:06 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.3.1-SNAPSHOT

### Minecraft Version

1.20.1

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Kubjs

### Expected Behavior

**The bronze firebox casing and I/O bus should display the motion map correctly.**

### Actual Behavior

 **However, the dynamic mapping of multi-block bronze oven is abnormal.**

- Like this...
![2024-08-18_03 53 37](https://github.com/user-attachments/assets/47ce4bbd-de46-493d-897a-b049e6c4c404)
![2024-08-18_03 53 43](https://github.com/user-attachments/assets/4edc54e5-8edc-4d39-b67c-761b80f605a5)

### Steps to Reproduce

You can see this phenomenon after correctly building a multi-block bronze oven and input steam and materials to make it run correctly.

### Additional Information

It seems that the rendering positions of the dynamic map and the block map overlap, which may be the cause of the problem?

**Comment by screret** [comment] 2024-08-17 20:17
Duplicate of #1723.

**Closed as not planned** 2024-08-17 20:17 UTC
Labels: type: bug
