### ISSUE TITLE
Server crash while holding pitchblende_dust for a while

### ISSUE THREAD

**Issue by JackieJK** [GregTechCEu/GregTechCEu-1.19#1635] opened 2024-08-02 06:13 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

REI

### Environment

Open to LAN

### Cross-Mod Interaction

Unsure

### Other Installed Mods

	Mod List: 
		server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: NOSIGNATURE
		configuration-forge-1.20.1-2.2.0.jar              |Configuration                 |configuration                 |2.2.0               |DONE      |Manifest: NOSIGNATURE
		[禁用聊天举报] NoChatReports-FORGE-1.20.1-v2.2.2.jar    |No Chat Reports               |nochatreports                 |1.20.1-v2.2.2       |DONE      |Manifest: NOSIGNATURE
		[玉 🔍] Jade-1.20.1-forge-11.9.4.jar               |Jade                          |jade                          |11.9.4+forge        |DONE      |Manifest: NOSIGNATURE
		[应用能源2] appliedenergistics2-forge-15.2.9.jar      |Applied Energistics 2         |ae2                           |15.2.9              |DONE      |Manifest: NOSIGNATURE
		lionfishapi-1.9.jar                               |LionfishAPI                   |lionfishapi                   |1.9                 |DONE      |Manifest: NOSIGNATURE
		[REI物品管理器] RoughlyEnoughItems-12.1.725-forge.jar  |Roughly Enough Items (REI)    |roughlyenoughitems            |12.1.725            |DONE      |Manifest: NOSIGNATURE
		[火花] spark-1.10.53-forge.jar                      |spark                         |spark                         |1.10.53             |DONE      |Manifest: NOSIGNATURE
		L_Enders_Cataclysm-1.99.6-1.20.1.jar              |Cataclysm Mod                 |cataclysm                     |1.99.5              |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.9.1+1.20.1.jar                     |Curios API                    |curios                        |5.9.1+1.20.1        |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.20.1-0.6.10-7.jar                |Flywheel                      |flywheel                      |0.6.10-7            |DONE      |Manifest: NOSIGNATURE
		[机械动力] create-1.20.1-0.5.1.f.jar                  |Create                        |create                        |0.5.1.f             |DONE      |Manifest: NOSIGNATURE
		[帕秋莉手册] Patchouli-1.20.1-84-FORGE.jar             |Patchouli                     |patchouli                     |1.20.1-84-FORGE     |DONE      |Manifest: NOSIGNATURE
		[Xaero的小地图] Xaeros_Minimap_24.2.0_Forge_1.20.jar  |Xaero's Minimap               |xaerominimap                  |24.2.0              |DONE      |Manifest: NOSIGNATURE
		[键位冲突显示] Controlling-forge-1.20.1-12.0.2.jar      |Controlling                   |controlling                   |12.0.2              |DONE      |Manifest: NOSIGNATURE
		[Xaero的世界地图] XaerosWorldMap_1.38.8_Forge_1.20.jar |Xaero's World Map             |xaeroworldmap                 |1.38.8              |DONE      |Manifest: NOSIGNATURE
		Searchables-forge-1.20.1-1.0.3.jar                |Searchables                   |searchables                   |1.0.3               |DONE      |Manifest: NOSIGNATURE
		[旅行者背包] travelersbackpack-forge-1.20.1-9.1.15.jar |Traveler's Backpack           |travelersbackpack             |9.1.15              |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.4.0-beta.2.jar                |MixinExtras                   |mixinextras                   |0.4.0-beta.2        |DONE      |Manifest: NOSIGNATURE
		[高级备份] AdvancedBackups-forge-1.20-3.6.jar         |Advanced Backups              |advancedbackups               |3.6                 |DONE      |Manifest: NOSIGNATURE
		architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |DONE      |Manifest: NOSIGNATURE
		[铁氧体磁芯] ferritecore-6.0.1-forge.jar               |Ferrite Core                  |ferritecore                   |6.0.1               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		ldlib-forge-1.20.1-1.0.25.p.jar                   |LowDragLib                    |ldlib                         |1.0.25.p            |DONE      |Manifest: NOSIGNATURE
		[格雷科技现代版] gtceu-1.20.1-1.3.1.jar                  |GregTech                      |gtceu                         |1.3.1               |DONE      |Manifest: NOSIGNATURE
		anvillib-forge-1.20.1-1.0.0+build.7.jar           |AnvilLib                      |anvillib                      |1.0.0+build.7       |DONE      |Manifest: NOSIGNATURE
		[铷 · 扩展] rubidium-extra-0.5.4.3+mc1.20.1-build.121|Embeddium Extra               |embeddium_extra               |0.5.4.3+mc1.20.1-bui|DONE      |Manifest: NOSIGNATURE
		[聊天头像] chat_heads-0.12.8-forge-1.20.jar           |Chat Heads                    |chat_heads                    |0.12.8              |DONE      |Manifest: NOSIGNATURE
		cloth-config-forge-11.1.118.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |DONE      |Manifest: NOSIGNATURE
		[物理声效重制版] sound-physics-remastered-forge-1.20.1-1.|Sound Physics Remastered      |sound_physics_remastered      |1.20.1-1.4.5        |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.3.0-universal.jar                 |Forge                         |forge                         |47.3.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		[苹果皮] appleskin-forge-mc1.20.1-2.5.1.jar          |AppleSkin                     |appleskin                     |2.5.1+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		embeddium-0.3.25+mc1.20.1.jar                     |Embeddium                     |embeddium                     |0.3.25+mc1.20.1     |DONE      |Manifest: NOSIGNATURE
		servux-forge-0.1.0-mc1.20.jar                     |Servux-Forge                  |servux                        |0.1.0-mc1.20        |DONE      |Manifest: NOSIGNATURE
		[铁砧工艺：原版科技] anvilcraft-forge-1.20.1-1.4.0.jar     |AnvilCraft                    |anvilcraft                    |1.4.0               |DONE      |Manifest: NOSIGNATURE
		[遗体] corpse-forge-1.20.1-1.0.12.jar               |Corpse                        |corpse                        |1.20.1-1.0.12       |DONE      |Manifest: NOSIGNATURE
		curtain-mc1.20.1-1.3.2.jar                        |Curtain                       |curtain                       |1.3.2               |DONE      |Manifest: NOSIGNATURE

### Expected Behavior

no crash

### Actual Behavior

I placed pitchblende_dust in the inventory, and after a while, the server crashes. Here are the logs from two instances.

[crash-2024-08-02_00.11.55-server.txt](https://github.com/user-attachments/files/16466164/crash-2024-08-02_00.11.55-server.txt)
[crash-2024-08-02_00.18.13-server.txt](https://github.com/user-attachments/files/16466165/crash-2024-08-02_00.18.13-server.txt)

### Steps to Reproduce

please check out the log

**Comment by screret** [comment] 2024-08-02 06:17
your server's lagging so much it gave up

**Comment by HiAndyFan** [comment] 2024-08-02 07:03
> your server's lagging so much it gave up

@screret The reason for the server lag seems to be related to medical_condition calculations. When a specific player carrying pitchblende_dust comes online, the server lags within a minute, then hits the max-tick-time limit and crashes. We tried the /gregtech medical_condition query command, which provides results for everyone else but gives no response for the player causing the server lag. When we removed the max-tick-time limit and reproduced the problem, the server lagged for about 3 minutes, after which the player died from cancer, and the server recovered from the lag.

**Comment by JackieJK** [comment] 2024-08-18 15:15
[profile by spark](https://spark.lucko.me/8mFjl4HdGD)

**Comment by screret** [comment] 2024-08-18 16:18
how is the item damage method causing so much lag?? it doesn't even do all that much

**Comment by JackieJK** [comment] 2024-08-18 16:37
> how is the item damage method causing so much lag?? it doesn't even do all that much

It's strange that the issue can only be reproduced with the save from that time; it can't be reproduced with later saves. I'll try testing it later using only the GTM.

**Comment by noobcoconut** [comment] 2024-08-19 07:13
did you have any armor with unbreaking enchantment on? I believe its fixed in #1560 try the latest version

**Closed as completed** 2024-08-19 07:20 UTC
Labels: type: bug

**Comment by JackieJK** [comment] 2024-08-19 07:30
> did you have any armor with unbreaking enchantment on? I believe its fixed in #1560 try the latest version

It seems to fit my situation, because the equipment on me has indeed disappeared.
