### ISSUE TITLE
ME Pattern Buffer (Major)

### ISSUE THREAD

**Issue by ramseyspace** [GregTechCEu/GregTechCEu-1.19#2382] opened 2024-11-17 02:19 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

Monifactory

### Minecraft Version

Monifactory 0.10.2

### Recipe Viewer Installed

EMI

### Environment

SinglePlayer

### Cross-Mod Interaction

No

### Other Installed Mods

Essential, world edit, flux networks, ae2 visualizer, and ae2 crafting tree mods

### Expected Behavior

To craft things that pattern was specifically placed in that bus to craft the cached items; its circuit and catalyst configurations. 

### Actual Behavior

When having several different circuit set in ME Pattern Buffer in one Extra Large Chemical reactor; The ELCR will make anything as anything inserts in *which makes some incorrect items*. Depends on how they behave. Sometimes left off at circuit 1 when it was meant to make circuit 24 stuff.

![image](https://github.com/user-attachments/assets/bc8c4148-376a-44d2-bfcb-fbb55ee32f9e)

### Steps to Reproduce

To reproduce, set 2-6+ ME Pattern buffers. Circuits set 0, 1, 2, 3, 4, 24 for each Buffer. All in one Extra Large Chemical Reactor multiblock. Set at least 1 pattern for every circuit and AE2 order all at once simultaneously. (Make dummy pattern) *Easier that way*

I suggest trying out Nitric Acid and Ammonia in circuit 24 along with other patterns in other circuits to make Ammonia or Nitric Acid. 

### Additional Information

I think ME Pattern Buffers is missing Input bus separation / missing support distant bus.

**Comment by Zorbatron** [comment] 2024-11-17 02:55
Duplicate of #1888

**Closed as not planned by Zorbatron** 2024-11-17 02:55 UTC
Labels: type: bug
