### ISSUE TITLE
Long distance item pipeline doesnt work

### ISSUE THREAD

**Issue by ghost** [GregTechCEu/GregTechCEu-1.19#1062] opened 2024-04-03 21:30 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.1.4

### Recipe Viewer Installed

JEI

### Environment

singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

custom modpack, but it started out as the  https://www.curseforge.com/minecraft/modpacks/gregtech-community-pack-modern pack. it doesnt work in the official modpack, nor any other modded circumstance. i have tested it thoroughly

### Expected Behavior

I expect items to transfer from one side to another

### Actual Behavior

doesnt do squat

### Steps to Reproduce

i placed at least 50 item pipeline blocks(60 in my case)
i then placed the end points in the right directions
i placed chests at the end points.
didnt work.
i also tried hooking up normal item pipes with covers from the chest and into the end points.

### Additional Information

no clue, very rarely actually works. even with nothing different in the setup. if this isnt bugged, what am i doing wrong

**Comment by screret** [comment] 2024-04-04 06:39
Duplicate of #978.

**Closed as not planned** 2024-04-04 06:40 UTC
Labels: type: bug
