### ISSUE TITLE
Crash upon loading into a world

### ISSUE THREAD

**Issue by H2GamingTW** [GregTechCEu/GregTechCEu-1.19#439] opened 2023-10-02 11:24 UTC
### GregTech CEu Version

1.19.2 fabric

### Recipe Viewer Installed

No Recipe Viewer

### Environment

singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

not crash

### Actual Behavior

crash

### Steps to Reproduce

make a instance with only fabric api and gt 
load into a new world

### Additional Information

what's weird is that if I add sodium and indium in it doesn't crash anymore, but the multiblock previews in REI/EMI/JEI becomes texture-less (just a black model)
edit: nvm even with sodium as soon as you mine any block in survival it crashes

log:
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2023-10-02 19:16:31
Description: Tessellating block in world - Indigo Renderer

java.lang.NoSuchMethodError: 'boolean net.minecraft.class_2680.supportsExternalFaceHiding()'
	at net.minecraft.class_2248.modifyExpressionValue$zmk000$porting_lib_extensions$customFaceHiding(class_2248.java:1679)
	at net.minecraft.class_2248.method_9607(class_2248.java:262)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.BlockRenderInfo.shouldDrawFace(BlockRenderInfo.java:108)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractQuadRenderer.renderQuad(AbstractQuadRenderer.java:70)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.renderQuad(TerrainFallbackConsumer.java:111)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:101)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:116)
	at net.minecraft.class_846$class_851$class_4578.redirect$zhd000$fabric-renderer-indigo$hookChunkBuildTesselate(class_846.java:786)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:578)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:489)
	at net.minecraft.class_846.method_22757(class_846.java:140)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2248.modifyExpressionValue$zmk000$porting_lib_extensions$customFaceHiding(class_2248.java:1679)
	at net.minecraft.class_2248.method_9607(class_2248.java:262)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.BlockRenderInfo.shouldDrawFace(BlockRenderInfo.java:108)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractQuadRenderer.renderQuad(AbstractQuadRenderer.java:70)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.renderQuad(TerrainFallbackConsumer.java:111)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:101)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:116)
	at net.minecraft.class_846$class_851$class_4578.redirect$zhd000$fabric-renderer-indigo$hookChunkBuildTesselate(class_846.java:786)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:578)

-- Block being tessellated --
Details:
	Block: Block{gtceu:rubber_leaves}[distance=4,persistent=false,waterlogged=false]
	Block location: World: (5,80,-32), Section: (at 5,0,0 in 0,5,-2; chunk contains blocks 0,-64,-32 to 15,319,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
Stacktrace:
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:116)
	at net.minecraft.class_846$class_851$class_4578.redirect$zhd000$fabric-renderer-indigo$hookChunkBuildTesselate(class_846.java:786)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:578)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:489)
	at net.minecraft.class_846.method_22757(class_846.java:140)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Affected level --
Details:
	All players: 1 total; [class_746['_TheKing6022_'/241, l='ClientLevel', x=7.50, y=87.00, z=-2.50]]
	Chunk stats: 961, 461
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,87,0), Section: (at 0,7,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 40 game time, 40 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_43589(class_310.java:856)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2142004736 bytes (2042 MiB) / 6341787648 bytes (6048 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a49
	Graphics card #0 versionInfo: DriverVersion=30.0.100.9864
	Graphics card #1 name: NVIDIA GeForce GTX 1660 Ti with Max-Q Design
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2191
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3168
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 29397.89
	Virtual memory used (MB): 18948.13
	Swap memory total (MB): 13312.00
	Swap memory used (MB): 279.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m
	Fabric Mods: 
		fabric-api: Fabric API 0.76.1+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.42+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.9+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.12+def3f86d90
			fabric-networking-v0: Fabric Networking (v0) 0.3.29+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.2+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.33+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.8+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabricloader: Fabric Loader 0.14.22
		gtceu: GregTech 1.0.12.g-build_216
			configuration: Configuration 2.1.0
			ldlib: LowDragLib 1.0.19.d
			registrate-fabric: Registrate for Fabric 1.1.58-MC1.19.2
				com_google_code_findbugs_jsr305: jsr305 3.0.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1032+1.19.2
					com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
					porting_lib_accessors: Porting Lib Accessors 2.1.1032+1.19.2
					porting_lib_attributes: Porting Lib Attributes 2.1.1032+1.19.2
					porting_lib_common: Porting Lib Common 2.1.1032+1.19.2
					porting_lib_constants: Porting Lib Constants 2.1.1032+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.1.1032+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.1.1032+1.19.2
					porting_lib_models: Porting Lib Models 2.1.1032+1.19.2
					porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1032+1.19.2
					porting_lib_transfer: Porting Lib Transfer 2.1.1032+1.19.2
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.2
	Launched Version: fabric-loader-0.14.22-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1660 Ti with Max-Q Design/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.68, NVIDIA Corporation
	Window size: 1920x986
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['_TheKing6022_'/241, l='ServerLevel[New World]', x=7.50, y=87.00, z=-2.50]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental

**Comment by screret** [comment] 2023-10-25 15:53
duplicate of #306

**Closed as not planned by screret** 2023-10-25 15:53 UTC
Labels: type: bug
