### ISSUE TITLE
Multiblock Render problem

### ISSUE THREAD

**Issue by Darmstadtium271** [GregTechCEu/GregTechCEu-1.19#1833] opened 2024-08-27 02:54 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.4.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

JEI, Jade, Jade Addons

### Expected Behavior

The buses and hatches should be rendered properly. The unformed multiblock is an example.
<img width="322" alt="image" src="https://github.com/user-attachments/assets/1b58c890-4007-4c67-bdf7-04956ac19beb">

### Actual Behavior

The textures of buses, hatches and multiblock controller overlaps, even in multiblock visulation.
![image](https://github.com/user-attachments/assets/94025442-fb8a-43e6-89d5-d226e7fbb222)
![image](https://github.com/user-attachments/assets/e408c4c2-3900-454b-82da-2855c1bb3b39)
![image](https://github.com/user-attachments/assets/f31eed63-88d9-46ed-a785-a299f639714d)

### Steps to Reproduce

Just build a multiblock and you'll find this problem.

**Comment by screret** [comment] 2024-08-28 06:08
duplicate of #1723 .

**Closed as not planned by screret** 2024-08-28 06:08 UTC
Labels: type: bug
