### ISSUE TITLE
large bronze boiler bugged ui

### ISSUE THREAD

**Issue by FabricioTrude** [GregTechCEu/GregTechCEu-1.19#2234] opened 2024-10-21 01:40 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.6

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory

### Expected Behavior

UI working

### Actual Behavior

![image](https://github.com/user-attachments/assets/7e97e074-f6cf-42c9-a61e-150853295372)

### Steps to Reproduce

place down bronze boiler

**Comment by Zorbatron** [comment] 2024-10-21 01:48
Duplicate of #2203

**Closed as not planned by Zorbatron** 2024-10-21 01:48 UTC
Labels: type: bug
