### ISSUE TITLE
multiplayer crash

### ISSUE THREAD

**Issue by IIIap** [GregTechCEu/GregTechCEu-1.19#1611] opened 2024-07-24 21:26 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Dedicated Server

### Cross-Mod Interaction

Unsure

### Other Installed Mods

ae2, cc:tweaked and others

### Expected Behavior

go back to menu after server off

### Actual Behavior

crashed

### Steps to Reproduce

1. be on server
2. off the server
3. click back to server list

### Additional Information

[crash-2024-07-25_00.19.20-client.txt](https://github.com/user-attachments/files/16367640/crash-2024-07-25_00.19.20-client.txt)

**Comment by forteen14desu** [comment] 2024-07-26 01:14
You can temporarily download the latest version of [ldlib](https://modrinth.com/mod/ldlib/versions) separately, which fixes compatibility issues with JEI. I think the GTM team will update the ldlib included in it soon :)
#https://github.com/Low-Drag-MC/LDLib-Architectury/issues/29

**Comment by screret** [comment] 2024-08-01 11:01
nvm

**Comment by screret** [comment] 2024-08-03 18:37
duplicate of #1525

**Closed as not planned by screret** 2024-08-03 18:37 UTC
Labels: type: bug
