### ISSUE TITLE
Logistic covers not importing if storage is placed afterwards

### ISSUE THREAD

**Issue by Deepacat** [GregTechCEu/GregTechCEu-1.19#1390] opened 2024-06-08 20:49 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.3.a

### Recipe Viewer Installed

No Recipe Viewer

### Environment

singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

solely gregtech issue

### Expected Behavior

When placing a logistics cover using import mode then placing a storage block, the logistics cover will not import the type

https://github.com/GregTechCEu/GregTech-Modern/assets/52133154/2b996928-c919-4a91-9ae5-443fe88a2389

https://github.com/GregTechCEu/GregTech-Modern/assets/52133154/fc6618c7-688e-4d35-9466-5a733d0fe5a6

### Actual Behavior

The cover does not update to recognize an existing storage and does not pull item/fluids

### Steps to Reproduce

Place pipe
Put cover on pipe, set to import
Place storage

### Additional Information

This is similar to when cables would not recognize new machines placed on them, and had to wirecut to update it
Happens for conveyors and pumps, any logistics cover on import

**Comment by screret** [comment] 2024-06-08 20:51
duplicate of #975, please comment this extra info on that issue.

**Closed as not planned** 2024-06-17 12:58 UTC
Labels: type: bug
