### ISSUE TITLE
Hi Amp Transformers Output Wrong Amperage and Fluctuating Voltage

### ISSUE THREAD

**Issue by MrNoe93** [GregTechCEu/GregTechCEu-1.19#615] opened 2023-12-08 18:42 UTC
### GregTech CEu Version

1.0.17

### Recipe Viewer Installed

JEI

### Environment

Singleplayer and Dedicated Server

### Cross-Mod Interaction

No

### Expected Behavior

When using a high voltage high amp 4x transformer, in step up mode, it would consume 16A HV and produce 4A EV.

### Actual Behavior

The transformer only produces 1A of a fluctuating voltage (between 1600 - 2500), enough to power 1 EV machine.  Tested this with the even higher amp power transformer and other voltages of high amp transformer and the same seems to be true.  The same happens with those transformers in step down mode as well.  The standard 1A - 4A transformers work as intended.  The wire used was high enough voltage and amperage to carry the expected amount.

### Steps to Reproduce

In creative, place down the high voltage high amp transformer and right click with a screwdriver to put into step up mode.  Place a creative energy source on the HV side and set the amperage, voltage, and make active.  On the EV side, attempt to run multiple EV mixers making tungsten carbide.  Only one will run and even it wont be able to fill its battery.

**Comment by 34486** [comment] 2023-12-14 23:50
Same is #584 or no? I thought I had a similar issue maybe not.

**Comment by MrNoe93** [comment] 2023-12-15 13:09
> Same is #584 or no? I thought I had a similar issue maybe not.

It does seem to be the same issue with the higher amp transformers.

**Comment by screret** [comment] 2024-01-13 20:13
seems to be a duplicate of #584

**Closed as not planned by screret** 2024-01-13 20:13 UTC
Labels: type: bug
