### ISSUE TITLE
Block data failing to load when updating to 1.5.2

### ISSUE THREAD

**Issue by teh-banana** [GregTechCEu/GregTechCEu-1.19#2374] opened 2024-11-15 13:48 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.5.2

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Monifactory 0.10.1 (manually updated GT)

### Expected Behavior

Not deleting covers on update

### Actual Behavior

:waaGONE:

### Steps to Reproduce

load save from 1.5.1 with block data (covers) or earlier in 1.5.2

### Additional Information

Lots of errors in the log about `Failed to load data for block entity`

Also, not all covers are being deleted, seems random

Also seems like kubejs machines are loading in weird. the controllers are empty until you look at them, then they load and form.

![2024-11-15_23 45 17](https://github.com/user-attachments/assets/7b9189b0-9a5d-4cd8-9d09-3051df7bbf5c)

Link to my latest.log: https://mclo.gs/vZ42ZRe

**Comment by Magespire** [comment] 2024-11-15 15:10
Done some light testing on a new instance with only gtm 1.5.2, jade, and EMI installed.

It looks like what's happening here is when the world is closed, ANY machine doing ANYTHING will have its data (contents, covers, muffle status, etc.) deleted when the world is loaded.

This is consistently reproducible by setting up a machine to constantly run with some covers, creating an identical machine that doesn't run, and closing the world. The running machines will always have all of the above issues upon loading the world.

I've attached a brief log showing the errors happening when machines have their data deleted upon world start, though I don't know how useful it'll be. There's nothing of note present in the logs when the world is closed.
[new 1.txt](https://github.com/user-attachments/files/17777310/new.1.txt)

Hope this helps.

**Closed as completed** 2024-11-16 02:50 UTC
Labels: type: bug
