### ISSUE TITLE
Quick moving items doesn't notify machine

### ISSUE THREAD

**Issue by Phoupraw** [GregTechCEu/GregTechCEu-1.19#594] opened 2023-11-28 16:28 UTC
### GregTech CEu Version

fabric-1.20.1-1.0.16

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

Holding shift clicking slot performs a quick move. It should notify machine to check its slots and starts working if it isn't working before as other item transfer ways.

### Actual Behavior

If a machine isn't working, and then quick moving items into machine slots, machine is still not working. Only taking off and re-putting the item into the machine (not by quick move) makes it start to work.

### Steps to Reproduce

1. Place a furnace.
2. Provide power to it.
3. Quick move logs or woods into it.
4. It doesn't start to work.

### Additional Information

Wasn't tested in forge.

**Comment by screret** [comment] 2023-11-28 16:32
duplicate of #357 .

**Closed as not planned by screret** 2023-11-28 16:32 UTC
Labels: type: bug
