### ISSUE TITLE
Crash game after join to the world (JEI compability)

### ISSUE THREAD

**Issue by dians1s** [GregTechCEu/GregTechCEu-1.19#1582] opened 2024-07-15 17:17 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.3.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

JEI v15.8.0.14

### Expected Behavior

Join to the world

### Actual Behavior

Crash game

### Steps to Reproduce

Install JEI and GTCEU the latest version.
Create World and get crash.

### Additional Information

Everything works well on gtceu version 1.2.2a, it was updated to 1.3.1 and started to crash when entering the world.

Here are the key points from the bug report:
GregTech (gtceu):
Version: 1.3.1
The error occurs in the GTOreVeinInfoCategory class on line 41.
The problem is related to the registerRecipes method.

Just Enough Items (jei):
Version: 15.3.0.4
The error occurs in the PluginLoader class on line 146.
The problem is related to the createRecipeManager method.
The main reason for the error is related to Mixin and InjectionError in the monazite fashion:

Error: Critical injection failure: Callback method setupText(Lcom/gregtechceu/gtceu/api/data/worldgen/GTOreDefinition;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in monazite.mixins.json:gtm.GTOreVeinWidgetMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap monazite-1.20.1-refmap.json.

**Comment by gateguardian523** [comment] 2024-07-15 22:20
Do not use monazite, it has already been merged into GTM

**Comment by qwer523** [comment] 2024-07-15 22:20
Do not use monazite, it has already been merged into GTM

**Comment by dians1s** [comment] 2024-07-16 07:59
> Do not use monazite, it has already been merged into GTM

Not work, i get crash with only JEI, with REI or delete JEI not problems

**Comment by dians1s** [comment] 2024-07-16 08:03
I even tried it on one of the builds, catching join to the world and have saving world -> crash on version 1.3.1. The crashlog: 
[crash-2024-07-16_12.59.14-client.txt](https://github.com/user-attachments/files/16245179/crash-2024-07-16_12.59.14-client.txt)

**Comment by Mindcool25** [comment] 2024-07-17 00:44
I'm running into the same issue, I can confirm that it crashes with a minimal setup with just JEI and GregTech installed on 1.20.1. I'll attache the crash report as well. The error seems to be different than the error in [this issue](https://github.com/GregTechCEu/GregTech-Modern/issues/876#issue-2119680655) but with similar symptoms.
Edit:
Just tried with REI, seems to work with that just fine.

**Comment by Lucky69420** [comment] 2024-07-17 07:22
same problem here only JEI and gregtech crashing when joining word

**Comment by KavisCorea** [comment] 2024-07-20 09:25
Going to follow up here saying that I believe I'm also having this issue in my modpack, I think my logs also point towards gregtech crashing with JEI being present. Although considering all my mods the issue I'm having could be different. But it crashes once I create the world as with everyone else here.

[crash-2024-07-20_02.21.00-client.txt](https://github.com/user-attachments/files/16319574/crash-2024-07-20_02.21.00-client.txt)
[latest.log](https://github.com/user-attachments/files/16319577/latest.log)

**Comment by Bingo-888** [comment] 2024-07-21 15:35
It happened to me too. My solution was to add a mod called "LowDragLib". It worked successfully.
Its Curseforge homepage: https://www.curseforge.com/minecraft/mc-mods/ldlib

**Closed as completed** 2024-07-27 12:33 UTC
Labels: type: bug

**Comment by kazimir-solan** [comment] 2024-08-18 19:29
I am not sure why this is closed. I am still encountering this error with a minimal setup consisting of GT 1.3.1, JEI 15.12.3.54, and LDLib 1.0.26.b.
[crash-2024-08-18_14.29.38-fml.txt](https://github.com/user-attachments/files/16651447/crash-2024-08-18_14.29.38-fml.txt)

**Comment by screret** [comment] 2024-08-18 19:37
because it's fixed.

**Comment by kazimir-solan** [comment] 2024-08-18 19:38
Well it sure doesn't seem to be.

**Comment by screret** [comment] 2024-08-18 19:39
well it is. in the development builds.
