### ISSUE TITLE
1.5.0 Crashes on Dedicated Server (1.20.1)

### ISSUE THREAD

**Issue by MefistoFereasy** [GregTechCEu/GregTechCEu-1.19#2335] opened 2024-11-13 20:58 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.5.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

None

### Environment

Dedicated Server

### Cross-Mod Interaction

No

### Other Installed Mods

I don't know what to write

### Expected Behavior

I don't know what to write

### Actual Behavior

Last logs and Crash 
[latest.log](https://github.com/user-attachments/files/17739223/latest.log)
[crash-2024-11-13_23.46.57-fml.txt](https://github.com/user-attachments/files/17739225/crash-2024-11-13_23.46.57-fml.txt)

### Steps to Reproduce

I don't know what to write

**Comment by YoungOnionMC** [comment] 2024-11-13 21:05
duplicate of #2329 
![image](https://github.com/user-attachments/assets/3ca8b3d1-fef8-489e-8466-76e92adf28d1)

**Comment by YoungOnionMC** [comment] 2024-11-13 21:06
and will be fixed in #2333

**Closed as not planned** 2024-11-13 21:07 UTC
Labels: type: bug
