### ISSUE TITLE
Crashing whilst opening some quests.

### ISSUE THREAD

**Issue by Lukasmftw** [GregTechCEu/GregTechCEu-1.19#570] opened 2023-11-21 17:16 UTC
### GregTech CEu Version

1.0.15

### Recipe Viewer Installed

JEI

### Environment

Dedicated server

### Cross-Mod Interaction

Yes

### Expected Behavior

Playing All the mods 9, their dev team believes this is a gregtech issue.

Step 1) open FTB quests.
Step 2) Open productive bees
Step 3) Click on glowstone bee quest
Step 4) Take the loot reward you get for completing quest
Step 5) Continue playing

OR 

Step 1) Open inventory
Step 2) Press middle mouse to sort
Step 3) Exit out of sorted inventory

### Actual Behavior

Step 1) open FTB quests.
Step 2) Open productive bees
Step 3) Click on glowstone bee quest/Sulfuric acid from Mekanism: Advanced
Step 4) Crash
Step 5) Dont open glowstone bee quest nor Sulfiric acid.

OR 

Step 1) Open inventory
Step 2) Press middle mouse to sort
Step 3) Get error in chat saying the same as screenshot in Additional Information
Step 4) Continue pressing middle mouse until it finally sorts the inventory
Step 5) Continue playing

### Steps to Reproduce

Step 1) open FTB quests.
Step 2) Open productive bees
Step 3) Click on glowstone bee quest
Step 4) Crash

OR 

Step 1) Open inventory
Step 2) Press middle mouse to sort
Step 3) Get error in chat saying the same as screenshot in Additional Information
Step 4) Continue pressing middle mouse until it finally sorts the inventory
Step 5) Continue playing

### Additional Information

[Crash report](https://mclo.gs/694uzQD)

I play ATM9 and once I try to open certain quests, I crash and get this error: [Crash report](https://mclo.gs/694uzQD)
I also get this error, but only in chat when I middle-mouse click, which sorts an inventory, and it doesn't crash.

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/94304646/f7a6ad8c-9181-4f6b-bebb-36998a9c67b8)

**Comment by screret** [comment] 2023-11-21 18:06
duplicate of #505.

**Closed as not planned by screret** 2023-11-21 18:06 UTC
Labels: type: bug
