### ISSUE TITLE
Filter cover crashes the save

### ISSUE THREAD

**Issue by robinxb** [GregTechCEu/GregTechCEu-1.19#2416] opened 2024-11-21 17:17 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.5.3

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

SP

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory

### Expected Behavior

Game not crash

### Actual Behavior

Game crash

### Steps to Reproduce

1) Place a tag cover on a gregtech chest and leave expr blank
2) change the input and output mode of the cover
3) game crash

===

I am not sure this can be repeated.

### Additional Information

Time: 2024-11-22 01:08:56
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "com.gregtechceu.gtceu.utils.TagExprFilter$TagExprParser$MatchExpr.matches(java.util.Set)" because "this.expr" is null
	at com.gregtechceu.gtceu.utils.TagExprFilter$TagExprParser$UnaryExpr.matches(TagExprFilter.java:87) ~[gtceu-1.20.1-1.5.3.jar%23450!/:1.5.3] {re:classloading}
	at com.gregtechceu.gtceu.utils.TagExprFilter.tagsMatch(TagExprFilter.java:285) ~[gtceu-1.20.1-1.5.3.jar%23450!/:1.5.3] {re:classloading}
	at com.gregtechceu.gtceu.api.cover.filter.TagItemFilter.test(TagItemFilter.java:48) ~[gtceu-1.20.1-1.5.3.jar%23450!/:1.5.3] {re:classloading}
	at com.gregtechceu.gtceu.api.cover.filter.TagItemFilter.test(TagItemFilter.java:19) ~[gtceu-1.20.1-1.5.3.jar%23450!/:1.5.3] {re:classloading}
	at com.gregtechceu.gtceu.common.cover.ConveyorCover.moveInventoryItems(ConveyorCover.java:241) ~[gtceu-1.20.1-1.5.3.jar%23450!/:1.5.3] {re:classloading}
	at com.gregtechceu.gtceu.common.cover.ConveyorCover.doTransferItems(ConveyorCover.java:227) ~[gtceu-1.20.1-1.5.3.jar%23450!/:1.5.3] {re:classloading}
	at com.gregtechceu.gtceu.common.cover.ConveyorCover.update(ConveyorCover.java:213) ~[gtceu-1.20.1-1.5.3.jar%23450!/:1.5.3] {re:classloading}
	at com.gregtechceu.gtceu.api.machine.TickableSubscription.run(TickableSubscription.java:23) ~[gtceu-1.20.1-1.5.3.jar%23450!/:1.5.3] {re:classloading}
	at com.gregtechceu.gtceu.api.machine.MetaMachine.executeTick(MetaMachine.java:293) ~[gtceu-1.20.1-1.5.3.jar%23450!/:1.5.3] {re:classloading}
	at com.gregtechceu.gtceu.api.machine.MetaMachine.serverTick(MetaMachine.java:265) ~[gtceu-1.20.1-1.5.3.jar%23450!/:1.5.3] {re:classloading}
	at com.gregtechceu.gtceu.api.block.IMachineBlock.lambda$getTicker$0(IMachineBlock.java:77) ~[gtceu-1.20.1-1.5.3.jar%23450!/:1.5.3] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?] {re:mixin,re:classloading,pl:mixin:APP:lithium.mixins.json:world.block_entity_ticking.world_border.DirectBlockEntityTickInvokerMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.WorldMixin,pl:mixin:APP:lithium.mixins.json:entity.collisions.intersection.WorldMixin,pl:mixin:APP:lithium.mixins.json:util.block_entity_retrieval.WorldMixin,pl:mixin:APP:lithium.mixins.json:util.block_tracking.block_listening.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.chunk_access.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.inline_block_access.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.inline_height.WorldMixin,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:gtceu.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:chunk.entity_class_groups.ServerWorldAccessor,pl:mixin:APP:lithium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:profiler.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.ServerWorldAccessor,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:gcyr.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23560!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) ~[?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:

**Comment by Ghostipedia** [comment] 2024-11-21 18:27
Duplicate of #2398 and resolved by PR #2402

**Closed as completed by Ghostipedia** 2024-11-21 18:27 UTC
Labels: type: bug
