### ISSUE TITLE
Variant stone ores can't be used for any recipes except forge hammering

### ISSUE THREAD

**Issue by JuiceyBeans** [GregTechCEu/GregTechCEu-1.19#1848] opened 2024-08-30 10:34 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Monifactory 0.8.1

### Expected Behavior

![image](https://github.com/user-attachments/assets/51eb6c57-d3ef-416f-b96a-ddaa26bd214b)
Has recipes for smelting, blasting, and macerating

### Actual Behavior

![image](https://github.com/user-attachments/assets/fb2a7069-f327-4cf5-9544-7e5ff92f0689)
Cannot be smelted, blasted, or macerated (not JEI jank, tested them and can't do them)

### Steps to Reproduce

Try slapping granite/andesite/etc. variant of an ore in a furnace or macerator

### Additional Information

While I'd recommend simply making the smelting/macerating recipes use the ``#forge:ores/whatever`` tag for the ore blocks right now, sometime in the future the macerating recipes should output the relevant stone dust (andesite dust, blackstone

**Comment by YoungOnionMC** [comment] 2024-08-30 20:58
duplicate of #1353

**Closed as not planned by YoungOnionMC** 2024-08-30 20:58 UTC
Labels: type: bug
