### ISSUE TITLE
Item bus bug

### ISSUE THREAD

**Issue by YiRanMushroom** [GregTechCEu/GregTechCEu-1.19#850] opened 2024-01-30 16:28 UTC
### GregTech CEu Version

gtceu-1.20.1-1.1.2-build_459

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

Item buses should function normally.

### Actual Behavior

Item input bus's gui is not set up correctly, and in the gui if the multiblock is formed, press R to an item would cause IllegalArgumentException, which causes game to crash:
Caused by: java.lang.IllegalArgumentException: Focus value is invalid: 0 air minecraft:air nbt:{}
	at mezz.jei.library.focus.Focus.createFromApi(Focus.java:84) ~[jei-1.20.1-forge-15.2.0.27.jar%23765!/:15.2.0.27]
	at mezz.jei.library.focus.FocusFactory.createFocus(FocusFactory.java:33) ~[jei-1.20.1-forge-15.2.0.27.jar%23765!/:15.2.0.27]
	at mezz.jei.gui.input.handlers.FocusInputHandler.lambda$createFocuses$1(FocusInputHandler.java:84) ~[jei-1.20.1-forge-15.2.0.27.jar%23765!/:15.2.0.27]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at mezz.jei.gui.input.handlers.FocusInputHandler.createFocuses(FocusInputHandler.java:86) ~[jei-1.20.1-forge-15.2.0.27.jar%23765!/:15.2.0.27]
	at mezz.jei.gui.input.handlers.FocusInputHandler.lambda$handleShow$0(FocusInputHandler.java:65) ~[jei-1.20.1-forge-15.2.0.27.jar%23765!/:15.2.0.27]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at mezz.jei.gui.input.handlers.FocusInputHandler.handleShow(FocusInputHandler.java:62) ~[jei-1.20.1-forge-15.2.0.27.jar%23765!/:15.2.0.27]
	at mezz.jei.gui.input.handlers.FocusInputHandler.handleUserInput(FocusInputHandler.java:49) ~[jei-1.20.1-forge-15.2.0.27.jar%23765!/:15.2.0.27]
	at mezz.jei.gui.input.handlers.CombinedInputHandler.handleClickInternal(CombinedInputHandler.java:42) ~[jei-1.20.1-forge-15.2.0.27.jar%23765!/:15.2.0.27]
	at mezz.jei.gui.input.handlers.CombinedInputHandler.handleUserInput(CombinedInputHandler.java:26) ~[jei-1.20.1-forge-15.2.0.27.jar%23765!/:15.2.0.27]
	at mezz.jei.gui.input.handlers.UserInputRouter.handleImmediateClick(UserInputRouter.java:50) ~[jei-1.20.1-forge-15.2.0.27.jar%23765!/:15.2.0.27]
	at mezz.jei.gui.input.handlers.UserInputRouter.handleUserInput(UserInputRouter.java:31) ~[jei-1.20.1-forge-15.2.0.27.jar%23765!/:15.2.0.27]
	at mezz.jei.gui.input.ClientInputHandler.onKeyboardKeyPressedPre(ClientInputHandler.java:42) ~[jei-1.20.1-forge-15.2.0.27.jar%23765!/:15.2.0.27]
	at mezz.jei.forge.startup.EventRegistration.lambda$registerClientInputHandler$1(EventRegistration.java:30) ~[jei-1.20.1-forge-15.2.0.27.jar%23765!/:15.2.0.27]
	at mezz.jei.core.util.WeakConsumer.accept(WeakConsumer.java:17) ~[jei-1.20.1-forge-15.2.0.27.jar%23765!/:15.2.0.27]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.client.ForgeHooksClient.onScreenKeyPressedPre(ForgeHooksClient.java:681) ~[forge-1.20.1-47.2.16-universal.jar%23975!/:?]
	at net.minecraft.client.KeyboardHandler.lambda$keyPress$5(KeyboardHandler.java:378) ~[client-1.20.1-20230612.114412-srg.jar%23970!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437) ~[client-1.20.1-20230612.114412-srg.jar%23970!/:?]
	... 26 more

Most guis are broken in this version.

### Steps to Reproduce

Form a multiblock structure with item buses and press R to check a recipe of an item in the inventory.

**Comment by screret** [comment] 2024-01-30 16:55
duplicate of #733

**Closed as not planned by screret** 2024-01-30 16:55 UTC
Labels: type: bug
