### ISSUE TITLE
Endless energy generation in Naquadah Reactor 1 per 1 bolt

### ISSUE THREAD

**Issue by z0the** [GregTechCEu/GregTechCEu-1.19#2150] opened 2024-10-12 11:06 UTC
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.4.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

ae2wtlib-15.2.3-forge.jar
AI-Improvements-1.20-0.5.2.jar
almostunified-forge-1.20.1-0.9.4.jar
antiblocksrechiseled-0.4.4.jar
appleskin-forge-mc1.20.1-2.5.1.jar
appliedenergistics2-forge-15.2.13.jar
architectury-9.2.14-forge.jar
athena-forge-1.20.1-3.1.2.jar
BadOptimizations-2.1.4-1.20.1.jar
badpackets-forge-0.4.3.jar
balm-forge-1.20.1-7.3.9-all.jar
betterfpsdist-1.20.1-4.4.jar
betterp2p-1.4.1-forge.jar
better_angel_ring-1.20.1-1.0.2.jar
bocchium-1.20.1-0.0.3.jar
Bountiful-6.0.3+1.20.1-forge.jar
buildinggadgets2-1.0.7.jar
CapeJS-1.0.0-1.20.1-forge.jar
cc-tweaked-1.20.1-forge-1.113.1.jar
cherishedworlds-forge-6.1.6+1.20.1.jar
Chipped-forge-1.20.1-3.0.6.jar
ChippedExpress-universal.jar
chisels-and-bits-forge-1.4.148.jar
chisel_chipped_integration-v1.1.3-1.20.1.jar
citresewn-1.20.1-5.jar
clienttweaks-forge-1.20-11.1.0.jar
climbladdersfast-4.0-1.20.1-forge.jar
cloth-config-11.1.118-forge.jar
Clumps-forge-1.20.1-12.0.0.4.jar
cofh_core-1.20.1-11.0.2.56.jar
collective-1.20.1-7.84.jar
configuration-forge-1.20.1-2.2.1.jar
configured-forge-1.20.1-2.2.3.jar
connectivity-1.20.1-5.6.jar
constructionwand-1.20.1-2.11.jar
Controlling-forge-1.20.1-12.0.2.jar
corpse-forge-1.20.1-1.0.14.jar
cosmeticarmorreworked-1.20.1-v1a.jar
craftingstation-1.20.1-1.jar
craftingtweaks-forge-1.20.1-18.2.5.jar
CreativeCore_FORGE_v2.11.37_mc1.20.1.jar
Cucumber-1.20.1-7.0.11.jar
CullLessLeaves-Reforged-1.20.1-1.0.5.jar
cupboard-1.20.1-2.7.jar
curios-forge-5.9.1+1.20.1.jar
DarkModeEverywhere-1.20.1-1.2.2.jar
defaultoptions-forge-1.20-18.0.1.jar
DefaultWorldType-1.20.1-4.0.4.jar
difficultylock-1.20.1-4.6.jar
Ding-1.20.1-Forge-1.5.0.jar
drippyloadingscreen_forge_3.0.1_MC_1.20.1.jar
EasyAnvils-v8.0.2-1.20.1-Forge.jar
effortlessbuilding-1.20.1-3.8.2.jar
elevatorid-1.20.1-lex-1.9.jar
embeddium-0.3.31+mc1.20.1.jar
embeddiumplus-1.20.1-v1.2.13.jar
emi-1.1.13+1.20.1+forge.jar
emi_loot-0.6.6+fix3+1.20.1+forge.jar
enderchests-forge-1.20.1-1.2.jar
EnderIO-1.20.1-6.2.0-beta-all.jar
endertanks-forge-1.20.1-1.3.jar
entityculling-forge-1.7.0-mc1.20.1.jar
ExtendedAE-1.20-1.1.12-forge.jar
ExtendedCrafting-1.20.1-6.1.5u.jar
ExtremeSoundMuffler-3.48-forge-1.20.1.jar
fancymenu_forge_3.2.3_MC_1.20.1.jar
FastFurnace-1.20.1-8.0.2.jar
FastLeafDecay-32.jar
FastSuite-1.20.1-5.0.1.jar
ferritecore-6.0.1-forge.jar
findme-3.2.1-forge.jar
fixexperiencebug-1.20-46.2.2.jar
FluxNetworks-1.20.1-7.2.0.14.jar
forgivingvoid-forge-1.20-10.0.1.jar
FpsReducer2-forge-1.20-2.5.jar
FramedBlocks-9.3.1.jar
framing_templates-1.0.1a.jar
ftb-chunks-forge-2001.3.1.jar
ftb-essentials-forge-2001.2.2.jar
ftb-library-forge-2001.2.4.jar
ftb-quests-forge-2001.4.8.jar
ftb-teams-forge-2001.3.0.jar
ftb-ultimine-forge-2001.1.5.jar
ftb-xmod-compat-forge-2.1.1.jar
ftbbackups2-forge-1.20-1.0.23.jar
fulleng-forge-1.7.2-1.20.1.jar
functionalstorage-1.20.1-1.2.12.jar
gcyr-1.20.1-0.2.3.jar
Glodium-1.20-1.5-forge.jar
gpumemleakfix-1.20.1-1.8.jar
gtceu-1.20.1-1.4.4.jar
HammerLib-1.20.1-20.1.32.jar
HangGlider-v8.0.1-1.20.1-Forge.jar
HostileNeuralNetworks-1.20.1-5.3.1.jar
Iceberg-1.20.1-forge-1.1.21.jar
iChunUtil-1.20.1-Forge-1.0.0.jar
ImmediatelyFast-Forge-1.2.21+1.20.4.jar
invtweaks-1.20.1-1.1.0.jar
ironfurnaces-1.20.1-4.1.6.jar
IronJetpacks-1.20.1-7.0.6.jar
item-filters-forge-2001.1.0-build.59.jar
Jade-1.20.1-forge-11.11.1.jar
JadeAddons-1.20.1-Forge-5.3.0.jar
JAVD-Forge-5.0.1+mc1.20.1.jar
jei-1.20.1-forge-15.14.0.64.jar
Kambrik-6.1.1+1.20.1-forge.jar
konkrete_forge_1.8.0_MC_1.20-1.20.1.jar
kotlinforforge-4.11.0-all.jar
kubejs-forge-2001.6.5-build.14.jar
kubejs-thermal-2001.1.10-build.2.jar
kubejs_enderio-forge-1.20.1-0.6.0.jar
laserio-1.6.8.jar
ldlib-forge-1.20.1-1.0.28.d.jar
LegendaryTooltips-1.20.1-forge-1.4.5.jar
Log-Begone-Forge-1.20.1-1.0.8.jar
lootjs-forge-1.20.1-2.12.0.jar
lootr-forge-1.20-0.7.34.89.jar
lostcities-1.20-7.3.2.jar
mae2-1.4.1.jar
megacells-forge-2.4.4-1.20.1.jar
melody_forge_1.0.3_MC_1.20.1-1.20.4.jar
merequester-forge-1.20.1-1.1.4.jar
modelfix-1.15.jar
modernfix-forge-5.19.3+mc1.20.1.jar
morejs-forge-1.20.1-0.10.0.jar
MouseTweaks-forge-mc1.20.1-2.25.1.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
Neat-1.20-35-FORGE.jar
nerb-1.20.1-0.3-FORGE.jar
no-telemetry-1.8.0.jar
NoChatReports-FORGE-1.20.1-v2.2.2.jar
noisium-forge-2.3.0+mc1.20-1.20.1.jar
nomowanderer-1.20.1_1.6.4.jar
nonetherportal-1.20.1-1.0.jar
notenoughcrashes-4.4.7+1.20.1-forge.jar
NuclearCraft-1.20.1-1.0.0-beta.6.jar
oculus-mc1.20.1-1.7.0.jar
open-parties-and-claims-forge-1.20.1-0.20.4.jar
PackagedAuto-1.20.1-3.4.7.25.jar
PackagedExCrafting-1.20.1-3.4.0.12.jar
PackagedExExCrafting-1.20.1-1.0.0.1.jar
Placebo-1.20.1-8.6.2.jar
polylib-forge-2000.0.3-build.143.jar
polymorph-forge-0.49.5+1.20.1.jar
PresenceFootsteps-1.20.1-1.9.1-beta.1.jar
Prism-1.20.1-forge-1.0.5.jar
PuzzlesLib-v8.1.23-1.20.1-Forge.jar
Quark-4.0-460.jar
radium-mc1.20.1-0.12.3+git.50c5c33.jar
redirector-5.0.0.jar
redstone_arsenal-1.20.1-8.0.1.24.jar
redstone_clock-1.1-1.20-1.20.1.jar
rehooked-1.5.1-1.20.1.jar
resourcefullib-forge-1.20.1-2.1.29.jar
rhino-forge-2001.2.3-build.6.jar
rubberdrawers-1.1.jar
Searchables-forge-1.20.1-1.0.3.jar
shetiphiancore-forge-1.20.1-1.3.jar
Shrink-1.20.1-1.4.5.jar
SimpleDiscordRichPresence-forge-4.0.3-build.40+mc1.20.1.jar
smoothboot(reloaded)-mc1.20.1-0.0.4.jar
smoothchunk-1.20.1-3.6.jar
Snad-1.20.1-Neo(Forge)-2.0.4.jar
SolarFluxReborn-1.20.1-20.1.6.jar
sophisticatedbackpacks-1.20.1-3.20.6.1064.jar
sophisticatedcore-1.20.1-0.6.25.632.jar
sophisticatedstorage-1.20.1-0.10.26.817.jar
spark-1.10.53-forge.jar
steamadditions-1.2.jar
steamdynamo-0.1.2.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.17a-forge-mc1.20.1.jar
systeams-1.20.1-1.7.1.jar
TelePastries-1.20.1-0.8.3.jar
temp.md
test.py
thermaldrawers-1.0.jar
thermal_expansion-1.20.1-11.0.1.29.jar
thermal_foundation-1.20.1-11.0.6.70.jar
thermal_innovation-1.20.1-11.0.1.23.jar
TipTheScales-forge-1.20.1-9.0.0.1.jar
titanium-1.20.1-3.8.32.jar
ToastControl-1.20.1-8.0.3.jar
toofast-1.20-0.4.3.5.jar
ToolBelt-1.20.1-1.20.01.jar
torchmaster-20.1.6.jar
trashcans-1.0.18b-forge-mc1.20.jar
trenzalore-forge-3.3.10+mc1.20.1-all.jar
trofers-forge-5.0.2.jar
ulvcovm-0.1.3.jar
watercollector-1.20.1-1.1.0.jar
waterframes-FORGE-mc1.20.1-v2.1.3.jar
watermedia-2.0.70.jar
waystones-forge-1.20-14.1.5.jar
wirelesschargers-1.0.9a-forge-mc1.20.jar
WWOO-FABRIC+FORGE+QUILT-2.0.0.jar
XaerosWorldMap_1.38.8_Forge_1.20.jar
Xaeros_Minimap_24.2.0_Forge_1.20.jar
xtonesreworked-1.0.3-F_1.20.1-47.2.0.jar
YeetusExperimentus-Forge-2.3.1-build.6+mc1.20.1.jar
Zeta-1.0-24.jar
zume-1.1.2.jar

### Expected Behavior

It is expected that at the beginning of energy generation and consumption of one bolt, when the dynamo hatch is filled with energy, the consumption progress should stop and not fall to zero (or continue to go and burn the bolt in vain)

### Actual Behavior

Now, when the dynamo hatch is fully filled, the bolt consumption progress drops to zero, and when there is free space for energy again, the process begins anew from scratch, endlessly using the same bolt. 
This can be easily used for endless free energy generation in naquadah reactor 1.

1) a screenshot of the filled dynamo hatch
![image](https://github.com/user-attachments/assets/7b35f205-1ff8-4e41-bd4c-6a3ad7f43210)

2) a screenshot of the progress that has managed to pass the time of full filling with energy
![image](https://github.com/user-attachments/assets/d808819c-69e0-49ef-a22b-7e7e46731a96)

3) a screenshot of the progress that has dropped to zero
![image](https://github.com/user-attachments/assets/c8bfceed-0024-41e0-8271-4b19e23b336b)

### Steps to Reproduce

Build a naquadah reactor 1 with a ZPM 4A Dynamo Hatch
Start a naquadah reactor 1, with any bolt(naquadria/enriched naquadah), do not consume energy from the reactor until it is filled with energy

### Additional Information

I'm not sure if this is a bug or a feature?

**Comment by Xefyr0** [comment] 2024-10-13 04:08
Duplicate of #1633 btw

**Comment by Spicierspace153** [comment] 2024-11-25 09:38
duplicate of #1633

**Closed as completed by Spicierspace153** 2024-11-25 09:38 UTC
Labels: type: bug, Wontfix
